import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import useHeadingObserver from "@/hooks/useHeadingObserver";

const Home: NextPage = () => {
  const { activeId, headings } = useHeadingObserver();

  const getClassName = (level: number) => {
    switch (level) {
      case 2:
        return "head2";
      case 3:
        return "head3";
      case 4:
        return "head4";
      default:
        return "";
    }
  };

  return (
    <div>
      <Head>
        <title>Table of Contents - oberserver example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Table of Content - observer example</h1>
        <a
          className="github"
          href="https://github.com/KahKitZheng/table-of-contents-observer"
          target="_blank"
          rel="noopener noreferrer"
        >
          Github - source code &rarr;
        </a>
      </header>

      <div className="wrapper">
        <aside>
          <p>Table of Contents</p>
          <ul>
            {headings.map((heading) => (
              <li key={heading.id} className={getClassName(heading.level)}>
                <Link href={`#${heading.id}`}>
                  <a
                    className={activeId === heading.id ? "active" : "inactive"}
                  >
                    {heading.text}
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </aside>

        <main className="content">
          <h2>Urna nunc id cursus</h2>
          <p>
            Consequat interdum varius sit amet mattis. Vitae nunc sed velit
            dignissim sodales ut. Augue ut lectus arcu bibendum at varius vel
            pharetra vel. Volutpat sed cras ornare arcu dui vivamus. Sit amet
            consectetur adipiscing elit duis tristique sollicitudin nibh sit.
            Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Ut eu
            sem integer vitae justo eget magna. Urna nunc id cursus metus.
            Ornare aenean euismod elementum nisi quis. Eu augue ut lectus arcu
            bibendum at varius. Cras tincidunt lobortis feugiat vivamus at augue
            eget arcu dictum. Aliquam vestibulum morbi blandit cursus risus at
            ultrices. Viverra accumsan in nisl nisi scelerisque eu ultrices
            vitae. Magnis dis parturient montes nascetur ridiculus mus. Ac odio
            tempor orci dapibus ultrices in iaculis nunc sed. Cursus risus at
            ultrices mi tempus imperdiet nulla malesuada pellentesque.
          </p>
          <h2>Eget mi proin</h2>
          <p>
            A scelerisque purus semper eget duis at tellus. Consectetur
            adipiscing elit duis tristique sollicitudin nibh. Ultrices in
            iaculis nunc sed augue lacus viverra. Cursus metus aliquam eleifend
            mi in nulla posuere sollicitudin. Nunc eget lorem dolor sed viverra
            ipsum. Bibendum est ultricies integer quis auctor elit sed. Laoreet
            sit amet cursus sit amet dictum sit. Eget mi proin sed libero.
            Pretium viverra suspendisse potenti nullam ac tortor vitae purus.
            Consequat mauris nunc congue nisi vitae suscipit. Dui ut ornare
            lectus sit amet est placerat. Hac habitasse platea dictumst quisque
            sagittis purus sit amet. Viverra nam libero justo laoreet sit. Urna
            nec tincidunt praesent semper feugiat nibh sed pulvinar. Ipsum nunc
            aliquet bibendum enim facilisis gravida neque. Vel pharetra vel
            turpis nunc eget lorem dolor sed. Ante metus dictum at tempor
            commodo ullamcorper a lacus vestibulum.
          </p>
          <h2>Ullamcorper velit sed</h2>
          <p>
            Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim
            diam. Ultrices sagittis orci a scelerisque. Tellus id interdum velit
            laoreet id donec ultrices tincidunt arcu. Amet volutpat consequat
            mauris nunc congue nisi. Massa sapien faucibus et molestie ac
            feugiat sed. Eget gravida cum sociis natoque penatibus et. Velit
            scelerisque in dictum non consectetur a. Mauris a diam maecenas sed
            enim. Tempor orci eu lobortis elementum. Mauris sit amet massa vitae
            tortor condimentum lacinia. Tristique senectus et netus et. Arcu
            felis bibendum ut tristique. Nam at lectus urna duis convallis.
            Lectus nulla at volutpat diam ut venenatis tellus in metus. Dui
            vivamus arcu felis bibendum ut tristique et egestas. Lacus viverra
            vitae congue eu consequat ac felis donec et. Ullamcorper velit sed
            ullamcorper morbi tincidunt ornare massa eget egestas. Amet nulla
            facilisi morbi tempus iaculis urna. Donec massa sapien faucibus et
            molestie.
          </p>
          <h2>Aliquam ultrices</h2>
          <p>
            Vitae aliquet nec ullamcorper sit. Viverra justo nec ultrices dui
            sapien eget mi proin sed. Vitae tempus quam pellentesque nec nam
            aliquam. Aliquam ultrices sagittis orci a scelerisque purus semper
            eget duis. Id aliquet risus feugiat in. Pellentesque id nibh tortor
            id aliquet lectus proin nibh nisl. Tincidunt eget nullam non nisi
            est sit. Integer vitae justo eget magna. In vitae turpis massa sed
            elementum. Rhoncus aenean vel elit scelerisque mauris.
          </p>
          <h2>Fusce ut placerat</h2>
          <p>
            Nibh venenatis cras sed felis eget velit aliquet sagittis. Odio eu
            feugiat pretium nibh ipsum consequat nisl vel. Pellentesque
            dignissim enim sit amet venenatis urna. Varius vel pharetra vel
            turpis nunc eget lorem dolor. Dolor morbi non arcu risus quis varius
            quam. Lectus mauris ultrices eros in cursus turpis. Eget magna
            fermentum iaculis eu non diam phasellus. Turpis cursus in hac
            habitasse. Purus in mollis nunc sed id. Tincidunt ornare massa eget
            egestas. Ultricies integer quis auctor elit sed vulputate mi sit.
            Faucibus purus in massa tempor nec. Mattis aliquam faucibus purus in
            massa tempor nec. Dictum at tempor commodo ullamcorper a lacus. Nibh
            tortor id aliquet lectus proin nibh. Fusce ut placerat orci nulla
            pellentesque. Tortor at auctor urna nunc id. Nunc sed id semper
            risus in hendrerit gravida rutrum. Risus viverra adipiscing at in
            tellus integer. Fermentum posuere urna nec tincidunt praesent semper
            feugiat nibh sed.
          </p>
          <h2>Aliquet risus</h2>
          <p>
            Nibh praesent tristique magna sit amet. Ultrices vitae auctor eu
            augue ut lectus arcu bibendum at. Sed sed risus pretium quam
            vulputate dignissim suspendisse. Est ullamcorper eget nulla facilisi
            etiam dignissim diam quis. Faucibus ornare suspendisse sed nisi
            lacus sed viverra tellus in. Mauris commodo quis imperdiet massa.
            Pulvinar mattis nunc sed blandit libero volutpat sed cras. Mauris
            pellentesque pulvinar pellentesque habitant morbi. Facilisi etiam
            dignissim diam quis enim lobortis scelerisque fermentum dui. Ornare
            quam viverra orci sagittis. Aliquet risus feugiat in ante. Aliquam
            ultrices sagittis orci a scelerisque purus semper eget duis.
            Ultrices eros in cursus turpis massa tincidunt dui. Ac feugiat sed
            lectus vestibulum mattis ullamcorper velit sed ullamcorper. Quisque
            egestas diam in arcu cursus. Tristique nulla aliquet enim tortor at
            auctor urna nunc.
          </p>
          <h3>Eu consequat</h3>
          <p>
            Habitant morbi tristique senectus et netus et malesuada fames ac.
            Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Eu
            consequat ac felis donec et odio pellentesque diam volutpat. Sit
            amet nisl suscipit adipiscing bibendum est. Enim praesent elementum
            facilisis leo vel fringilla est ullamcorper. Amet consectetur
            adipiscing elit pellentesque habitant morbi tristique senectus. Arcu
            dui vivamus arcu felis bibendum ut tristique et egestas. Venenatis
            urna cursus eget nunc scelerisque viverra mauris. Cursus metus
            aliquam eleifend mi in nulla posuere sollicitudin. Elementum tempus
            egestas sed sed. Cras sed felis eget velit aliquet sagittis.
            Ultrices dui sapien eget mi proin sed libero. Morbi blandit cursus
            risus at ultrices mi tempus imperdiet nulla. Dictum at tempor
            commodo ullamcorper a lacus. Consectetur lorem donec massa sapien
            faucibus et molestie.
          </p>
          <h4>Non enim</h4>
          <p>
            Sapien et ligula ullamcorper malesuada proin libero nunc consequat.
            Mi quis hendrerit dolor magna eget est. Elementum nibh tellus
            molestie nunc non blandit. Tortor dignissim convallis aenean et
            tortor at risus. Morbi quis commodo odio aenean sed. Euismod lacinia
            at quis risus. Enim sit amet venenatis urna cursus. Nunc non blandit
            massa enim nec dui nunc. Tristique sollicitudin nibh sit amet
            commodo nulla facilisi nullam vehicula. In vitae turpis massa sed
            elementum tempus egestas sed. Faucibus interdum posuere lorem ipsum
            dolor sit amet consectetur. Mattis rhoncus urna neque viverra justo
            nec ultrices dui sapien. Id aliquet risus feugiat in ante. Egestas
            tellus rutrum tellus pellentesque. Massa enim nec dui nunc mattis
            enim ut tellus. Sem viverra aliquet eget sit amet. Non enim praesent
            elementum facilisis leo vel.
          </p>
          <h2>Porttitor massa id neque</h2>
          <p>
            Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Felis
            imperdiet proin fermentum leo vel orci porta. Sed arcu non odio
            euismod lacinia. Rhoncus mattis rhoncus urna neque. Accumsan sit
            amet nulla facilisi morbi tempus. Sit amet luctus venenatis lectus.
            Quis viverra nibh cras pulvinar mattis. Porttitor massa id neque
            aliquam. Pretium fusce id velit ut. Sollicitudin aliquam ultrices
            sagittis orci a scelerisque. Amet cursus sit amet dictum sit amet
            justo. Maecenas pharetra convallis posuere morbi leo urna molestie
            at elementum. Lectus sit amet est placerat in egestas erat. Interdum
            consectetur libero id faucibus nisl. Est velit egestas dui id
            ornare. Enim sit amet venenatis urna cursus eget nunc scelerisque
            viverra. Sit amet consectetur adipiscing elit ut aliquam purus.
            Tristique et egestas quis ipsum suspendisse ultrices gravida. In est
            ante in nibh mauris cursus mattis. In egestas erat imperdiet sed
            euismod nisi.
          </p>
          <h2>Vel elit scelerisque</h2>
          <p>
            Eu mi bibendum neque egestas congue quisque. Scelerisque eleifend
            donec pretium vulputate sapien nec sagittis aliquam malesuada. Sem
            integer vitae justo eget. Sed faucibus turpis in eu mi bibendum. Vel
            eros donec ac odio tempor orci dapibus ultrices in. Mattis
            pellentesque id nibh tortor id aliquet lectus proin nibh. Sagittis
            id consectetur purus ut faucibus. Turpis massa tincidunt dui ut
            ornare lectus sit. Vel elit scelerisque mauris pellentesque pulvinar
            pellentesque habitant morbi tristique. Semper viverra nam libero
            justo laoreet sit amet. Ac felis donec et odio pellentesque diam.
            Facilisi cras fermentum odio eu. Etiam erat velit scelerisque in
            dictum non consectetur a erat. Tempor id eu nisl nunc mi ipsum
            faucibus. Malesuada fames ac turpis egestas sed tempus urna. Orci eu
            lobortis elementum nibh tellus molestie nunc non blandit.
          </p>
          <h2>Maecenas pharetra</h2>
          <p>
            Risus viverra adipiscing at in tellus integer. Tortor pretium
            viverra suspendisse potenti. Pretium viverra suspendisse potenti
            nullam ac tortor vitae. Nullam non nisi est sit amet facilisis magna
            etiam tempor. Massa ultricies mi quis hendrerit dolor. Nunc
            consequat interdum varius sit amet. Donec massa sapien faucibus et
            molestie ac feugiat sed lectus. Faucibus scelerisque eleifend donec
            pretium vulputate sapien nec sagittis aliquam. Arcu non odio euismod
            lacinia at quis risus sed vulputate. Et molestie ac feugiat sed
            lectus vestibulum mattis ullamcorper velit. Vel pharetra vel turpis
            nunc eget lorem dolor sed. Non odio euismod lacinia at quis risus.
            Integer malesuada nunc vel risus commodo. Lacus vel facilisis
            volutpat est velit egestas. Pulvinar neque laoreet suspendisse
            interdum consectetur libero. Tincidunt dui ut ornare lectus sit amet
            est placerat in. Erat imperdiet sed euismod nisi porta lorem. Urna
            nec tincidunt praesent semper feugiat nibh sed pulvinar. Maecenas
            pharetra convallis posuere morbi leo urna molestie at elementum.
          </p>
          <h2>Non odio euismod</h2>
          <p>
            Risus viverra adipiscing at in tellus integer. Tortor pretium
            viverra suspendisse potenti. Pretium viverra suspendisse potenti
            nullam ac tortor vitae. Nullam non nisi est sit amet facilisis magna
            etiam tempor. Massa ultricies mi quis hendrerit dolor. Nunc
            consequat interdum varius sit amet. Donec massa sapien faucibus et
            molestie ac feugiat sed lectus. Faucibus scelerisque eleifend donec
            pretium vulputate sapien nec sagittis aliquam. Arcu non odio euismod
            lacinia at quis risus sed vulputate. Et molestie ac feugiat sed
            lectus vestibulum mattis ullamcorper velit. Vel pharetra vel turpis
            nunc eget lorem dolor sed. Non odio euismod lacinia at quis risus.
            Integer malesuada nunc vel risus commodo. Lacus vel facilisis
            volutpat est velit egestas. Pulvinar neque laoreet suspendisse
            interdum consectetur libero. Tincidunt dui ut ornare lectus sit amet
            est placerat in. Erat imperdiet sed euismod nisi porta lorem. Urna
            nec tincidunt praesent semper feugiat nibh sed pulvinar. Maecenas
            pharetra convallis posuere morbi leo urna molestie at elementum.
          </p>
          <h2>Egestas purus viverra</h2>
          <p>
            Sit amet facilisis magna etiam tempor. In aliquam sem fringilla ut
            morbi tincidunt augue. Egestas purus viverra accumsan in. Fusce ut
            placerat orci nulla pellentesque. Volutpat sed cras ornare arcu dui
            vivamus. Commodo viverra maecenas accumsan lacus vel facilisis
            volutpat. Sed viverra ipsum nunc aliquet bibendum. Vestibulum
            rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt
            lobortis. Ultricies mi quis hendrerit dolor magna eget. Non quam
            lacus suspendisse faucibus interdum. In nibh mauris cursus mattis
            molestie. Ac tortor dignissim convallis aenean. Pulvinar elementum
            integer enim neque volutpat. Risus sed vulputate odio ut enim
            blandit volutpat maecenas volutpat. Enim ut sem viverra aliquet eget
            sit amet. Euismod elementum nisi quis eleifend. Convallis a cras
            semper auctor neque vitae tempus. At elementum eu facilisis sed odio
            morbi quis commodo. Erat velit scelerisque in dictum non consectetur
            a erat.
          </p>
          <h2>Pretium nibh</h2>
          <p>
            Facilisis gravida neque convallis a cras semper auctor neque.
            Habitasse platea dictumst quisque sagittis. Est placerat in egestas
            erat imperdiet sed. Elit ullamcorper dignissim cras tincidunt
            lobortis feugiat vivamus. Gravida in fermentum et sollicitudin ac
            orci phasellus. Etiam non quam lacus suspendisse. Eleifend quam
            adipiscing vitae proin sagittis. Elit at imperdiet dui accumsan sit
            amet nulla facilisi. Purus faucibus ornare suspendisse sed. Dis
            parturient montes nascetur ridiculus. Sit amet consectetur
            adipiscing elit ut aliquam purus sit amet. Mauris nunc congue nisi
            vitae. Donec ac odio tempor orci. Pretium nibh ipsum consequat nisl
            vel pretium lectus quam id. Lorem ipsum dolor sit amet consectetur
            adipiscing elit pellentesque. Semper risus in hendrerit gravida
            rutrum quisque. Pellentesque nec nam aliquam sem et tortor consequat
            id. Egestas sed tempus urna et. Semper viverra nam libero justo. Vel
            orci porta non pulvinar.
          </p>
          <h2>Posuere sollicitudin</h2>
          <p>
            Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque
            elit. Tincidunt eget nullam non nisi est sit amet facilisis. Orci
            porta non pulvinar neque laoreet suspendisse interdum. Id interdum
            velit laoreet id donec ultrices tincidunt arcu. Adipiscing elit
            pellentesque habitant morbi tristique senectus et netus et. Nunc id
            cursus metus aliquam eleifend mi. In pellentesque massa placerat
            duis ultricies lacus sed. Risus sed vulputate odio ut enim blandit
            volutpat maecenas. Dignissim cras tincidunt lobortis feugiat. Sit
            amet mattis vulputate enim nulla. Posuere sollicitudin aliquam
            ultrices sagittis orci a scelerisque purus. Tortor dignissim
            convallis aenean et tortor at risus viverra adipiscing. Velit sed
            ullamcorper morbi tincidunt ornare massa eget. Mollis nunc sed id
            semper risus in. Ultrices dui sapien eget mi proin sed libero enim.
            Enim ut tellus elementum sagittis vitae et leo duis. Quam quisque id
            diam vel quam elementum.
          </p>
        </main>
      </div>
    </div>
  );
};

export default Home;
